### PR TITLE
Generalise exceptions and fix regression

### PR DESCRIPTION
**Pull request by phala**

### CODE REVIEW

**Comment by phala** [comment]
Hi @owais. Could you please have a look at this?

**Comment by owais** [comment]
Looks good. Thanks.

**Comment by owais** [comment]
Could this be a breaking change? Could people trying to catch one of the exception deriving from WebpackError unexpectedly catch bare WebpackError? 

I'd suggest to add a new `BaseWebpackException` or `BaseWebpackError` and inherit everything from it including the `WebpackError`

**Comment by phala** [comment]
@owais part of the reason why I'm proposing this change is to maintain backwards compatibility, and so that one could catch all the exceptions from `django-webpack-loader` in one go. With the current state, all the exceptions are raised in `get_bundle`. 

`WebpackError` is used in only one place. I think it might be better to leave that one as is, and let the place where it is used [(like here)](https://github.com/ezhome/django-webpack-loader/blob/master/webpack_loader/loader.py#L96) raise a new error which inherits from this one. I don't see this causing issues.

**Comment by owais** [comment]
The problem is that WebpackError specifically exists to represent an error that happened in webpack process itself while as other exceptions represent errors happening in python code. So it doesn't seem to be correct to extend other exceptions from WebpackError. Wouldn't your problem be solved if you add a new `BaseWebpackLoaderException` and then extend all other exceptions from this? You can then catch `BaseWebpackLoaderException` to catch all errors from the package.

**Comment by phala** [comment]
@owais done. Thanks.

**Comment by owais** [comment]
Thanks

**Pull request merged**
